### ISSUE TITLE
Drag & Drop in a GridLayoutManager

### ISSUE THREAD

**Issue by ruckus** [ismoli/DynamicRecyclerView#3]
Thanks for the fantastic library.

I'm trying to implement drag-and-drop with a GridLayoutManager.

In my `Activity.onCreate` I have declared the grid:

```
recyclerView.setLayoutManager(new GridLayoutManager(this, 2));
```

And I do get a grid of 2 columns. However, when I go into drag-and-drop mode I can only move within the column, I cannot move left or right.

I'm pretty sure I need to muck around in `DragDropTouchListener.switchViewsIfNeeded` but I'm not sure. 

Any suggestions on how to tackle this? Thanks!

**Comment by ismoli** [comment]
I wasn't actually testing it with GridLayoutManager as this lib is more like example of what could be done, however first thing you should look at is that views are only move by Y axis, so you'd need to change this... that _probably_ would be enough..

**Comment by ruckus** [comment]
Thank you for the suggestion, that was what I needed. I successfully implemented X/Y axis dragging/dropping.  You were right - I just needed to account for the X axis movement.

Here is a Gist to my listener.

https://gist.github.com/ruckus/a4f831d8dce785c91aed

If you would like me to fork your repo and provide a pull-request with this addition then just let me know.

Thanks again!

**Comment by ismoli** [comment]
Hi, great, yes, I believe community will benefit if you provide implementation for a GridLayout, thanks!

**Comment by danksky** [comment]
Hello, I'm very rookie when it comes to pulling off other projects' APIs and implementing some of their code into my own. I want to include features for my RecyclerView like bringing up a contextual action bar with ease upon long clicking a card, or swiping cards to archive them. I don't understand how I can implement your code to my own so that I can design a new function for, say, swiping, so that the swiped card does what { I } desire to do, but with the ease that your sample code shows. Please help or set me in the right direction?
